await figma.setCurrentPageAsync(await figma.getNodeByIdAsync('506:25'));
await Promise.all(['Regular','Medium','SemiBold'].map(style=>figma.loadFontAsync({family:'Poppins',style})));
const created=[],mutated=[];
const vars={};for(const [k,id]of Object.entries(STATE.variables))vars[k]=await figma.variables.getVariableByIdAsync(id);
function track(n){created.push(n.id);return n}
function paint(k='white'){return figma.variables.setBoundVariableForPaint({type:'SOLID',color:{r:1,g:1,b:1}},'color',vars[k]);}
function rectRadius(n,r=27){n.cornerRadius=r;if(r===27||r===999){for(const k of ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius'])n.setBoundVariable(k,vars[r===27?'card':'pill']);}}
function box(parent,name,w=351,gap=12,pad=0,bg=null,dir='VERTICAL'){const n=track(figma.createAutoLayout(dir));n.name=name;n.fills=bg?[paint(bg)]:[];n.resize(w,1);n.layoutSizingHorizontal='FIXED';n.layoutSizingVertical='HUG';n.itemSpacing=gap;n.paddingTop=n.paddingBottom=n.paddingLeft=n.paddingRight=pad;if(gap===12)n.setBoundVariable('itemSpacing',vars.gap);if(parent)parent.appendChild(n);return n;}
function txt(p,s,size=13,weight='Regular',color='ink',width=null){const n=track(figma.createText());n.name=s.slice(0,55);n.fontName={family:'Poppins',style:weight};n.fontSize=size;n.lineHeight={unit:'PIXELS',value:Math.round(size*(size>=24?1.2:1.55))};n.characters=s;n.fills=[paint(color)];p.appendChild(n);if(width!==null){n.resize(width,n.height);n.textAutoResize='HEIGHT';}else{n.layoutSizingHorizontal='FILL';n.textAutoResize='HEIGHT';}if(size>=24)n.letterSpacing={unit:'PIXELS',value:-.7};return n;}
function icon(p,key,size=20,color='ink'){const hex={ink:'#131312',muted:'#77766f',white:'#ffffff'}[color]||'#131312';const n=figma.createNodeFromSvg(ICONS[key].replaceAll('currentColor',hex));n.name=key;n.resize(size,size);p.appendChild(n);created.push(n.id,...n.findAll(()=>true).map(c=>c.id));return n;}
function instance(p,key,w){const n=track(COMP[key].createInstance());p.appendChild(n);if(w)n.resize(w,n.height);return n;}
function button(p,label,secondary=false){const n=instance(p,secondary?'secondary':'primary',p.width-p.paddingLeft-p.paddingRight);n.setProperties({[STATE.buttonProp[secondary?'secondary':'primary']]:label});n.name='Action / '+label;return n;}
function field(p,label,value,multi=false){const n=box(p,'Field / '+label,p.width-p.paddingLeft-p.paddingRight,7);txt(n,label,11,'Medium','muted');const f=instance(n,'input',n.width);f.setProperties({[STATE.inputProp]:value});if(multi)f.resize(n.width,value.length>110?150:110);return f;}
function chips(p,options,selected=0){const n=box(p,'Choices',p.width-p.paddingLeft-p.paddingRight,6,0,null,'HORIZONTAL');n.layoutWrap='WRAP';for(let i=0;i<options.length;i++){const c=instance(n,i===selected?'chipOn':'chipOff');c.setProperties({[STATE.chipProp[i===selected?'chipOn':'chipOff']]:options[i]});c.resize(Math.max(42,options[i].length*6.4+24),36);}return n;}
function tag(p,s){const n=box(p,'Badge',Math.max(66,s.length*5.3+16),0,7,'cream');rectRadius(n,999);txt(n,s,9,'Medium','muted');return n;}
function avatar(p,s){const n=box(p,'Avatar',36,0,0,'cream');n.resize(36,36);n.layoutSizingVertical='FIXED';n.primaryAxisAlignItems='CENTER';n.counterAxisAlignItems='CENTER';rectRadius(n,999);const t=txt(n,s,10,'Medium','ink',24);t.textAlignHorizontal='CENTER';return n;}
function person(p,initial,name,role){const n=box(p,'Person',p.width-p.paddingLeft-p.paddingRight,10,0,null,'HORIZONTAL');n.counterAxisAlignItems='CENTER';avatar(n,initial);const c=box(n,'Identity',n.width-48,1);txt(c,name,12,'Medium');txt(c,role,10,'Regular','muted');return n;}
function card(p,title='',bg='white'){const n=box(p,'Card / '+title,p.width-p.paddingLeft-p.paddingRight,12,20,bg);n.strokes=[paint('line')];n.strokeWeight=1;rectRadius(n);if(title)txt(n,title,24,'Medium');return n;}
function details(p,lines){const n=box(p,'Details',p.width-p.paddingLeft-p.paddingRight,10);for(let i=0;i<lines.length;i++){const r=box(n,'Detail',n.width,8,0,null,'HORIZONTAL');r.counterAxisAlignItems='CENTER';icon(r,['ClockIcon','SewingPinIcon','PersonIcon'][i%3],15,'muted');txt(r,lines[i],12,'Regular','ink',n.width-24);}return n;}
function note(p,s){const n=box(p,'Supporting note',p.width-p.paddingLeft-p.paddingRight,0,12,'soft');rectRadius(n,18);txt(n,s,10,'Regular','muted');return n;}
function post(p,name,role,copy,type='Interest check'){const c=card(p,'','soft');person(c,name==='Alex Lin'?'AL':'MC',name,role);tag(c,type);txt(c,copy,13);details(c,['After work','Campus A']);const r=box(c,'Response',c.width-40,7,0,null,'HORIZONTAL');icon(r,'HeartIcon',15);txt(r,'I’m interested',11,'Medium');return c;}
function topic(p,name='Zoe Lin',role='Product Designer',title='Design to product. The honest version.'){const c=card(p);person(c,name==='Zoe Lin'?'ZL':'RX',name,role);tag(c,'I can share');txt(c,title,23,'Medium');txt(c,name==='Zoe Lin'?'What surprised me when I moved into product, and what I wish I’d known.':'Turning a messy wall of research into a decision the team can use.',13,'Regular','muted');button(c,'Explore this topic',true);return c;}
function bubble(p,s){const n=box(p,'Your words',p.width-p.paddingLeft-p.paddingRight,0,16,'bubble');rectRadius(n,24);txt(n,s,13);return n;}
function assistant(p,q,copy){txt(p,'TODAY · JUST FOR YOU',9,'Regular','muted');if(q)bubble(p,q);txt(p,'OVERLAP',10,'Medium','muted');txt(p,copy,14);}
function prefs(p){txt(p,'Campus',11,'Medium','muted');chips(p,['Campus A','Campus B']);field(p,'Lunch time','12:00');txt(p,'Table size',11,'Medium','muted');chips(p,['2','4']);txt(p,'Food preferences',11,'Medium','muted');chips(p,['Vegetarian','No restrictions']);txt(p,'Draw timing',11,'Medium','muted');chips(p,['Instant','Scheduled']);txt(p,'Private matching settings. A 10-minute walk is the maximum. We will ask before changing these conditions.',10,'Regular','muted');}
function profile(p){const c=card(p,'','cream');person(c,'MC','Mia Chen','Product Designer');tag(c,'Public preview');txt(c,'New to the team. Into photography, long walks and good questions.',14);chips(c,['Photography','Walking']);return c;}
function screen(row,name,header='overlap',nav='Home',chat=false){const holder=box(row,name,393,12);const lab=txt(holder,name,12,'Medium','muted');const s=box(holder,'Screen / '+name,393,0,0,'white');rectRadius(s,32);s.clipsContent=true;const top=box(s,'Top safe area',393,0,0);top.resize(393,28);top.layoutSizingVertical='FIXED';const h=box(s,'App header',393,12,22,null,'HORIZONTAL');h.paddingTop=8;h.paddingBottom=16;h.counterAxisAlignItems='CENTER';if(header!=='overlap')icon(h,'ArrowLeftIcon');txt(h,header,header==='overlap'?28:16,'SemiBold','ink',header==='overlap'?290:272);if(header==='overlap'){const a=avatar(h,'MC');a.fills=[paint('ink')];for(const t of a.findAllWithCriteria({types:['TEXT']}))t.fills=[paint('white')];}const body=box(s,'Scrollable content',393,18,22);body.paddingTop=10;body.paddingBottom=24;body.minHeight=620;let bottom;if(chat){bottom=box(s,'Composer',393,5,18,'white');bottom.strokes=[paint('line')];const r=box(bottom,'Message input',357,8,0,null,'HORIZONTAL');txt(r,'Tell me more, or change a detail…',11,'Regular','muted',310);icon(r,'ArrowUpIcon',20);txt(bottom,'AI demo · nothing is sent without your choice',8,'Regular','muted');}else{bottom=instance(s,'nav',393);for(const n of bottom.findAllWithCriteria({types:['FRAME']})){if(n.name.startsWith('Nav / ')){n.fills=[paint(n.name==='Nav / '+nav?'ink':n.name==='Nav / Create'?'accent':'white')];const isOn=n.name==='Nav / '+nav;for(const v of n.findAllWithCriteria({types:['VECTOR']}))if(v.fills.length)v.fills=[paint(isOn?'white':'ink')];}}}const safe=box(s,'Bottom safe area',393,0,0,'white');safe.resize(393,22);safe.layoutSizingVertical='FIXED';return{holder,s,body};}
const COMP={};for(const[k,id]of Object.entries(STATE.components||{}))COMP[k]=await figma.getNodeByIdAsync(id);
